### Crear usuario
POST  http://localhost:5000/users/signup
content-type: application/json

{
  "username": "test01",
  "email": "test01@gmail.com",
  "password": "1231234"
}

### Crear usuario con rol
POST  http://localhost:5000/users/signup
content-type: application/json

{
  "username": "admin01",
  "email": "admin01@gmail.com",
  "password": "1231234",
  "roles": "admin"
}