### Crear un producto
POST  http://localhost:5000/products/
content-type: application/json

{
  "name": "Mantenimiento Preventivo",
  "description": "Mantenimiento y limpieza programada para prevenir fallas",
  "type":"Service",
  "price": 8762
}


### Buscar todos los productos
GET http://localhost:5000/products


### Buscar un producto por id
GET http://localhost:5000/products/65456306754f9595cbe63d6b


### Actualizar un cliente por id
PUT   http://localhost:5000/products/6545635b754f9595cbe63d6d
content-type: application/json

{
  "price": 10514
}


### Eliminar un producto por id
DELETE http://localhost:5000/clients/productId