### Crear un producto
POST  http://localhost:5000/products/
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDZhN2RlZGNhMjE2OGRhNTgwY2I3ZiIsImlhdCI6MTY5OTE1Mzg2OCwiZXhwIjoxNjk5MTYxMDY4fQ.EUbhvq2DnqMEPtwlYbA0cZ8c4fd3vsp_JYtn3eGtrIg


{
  "name": "Mantenimiento Preventivo",
  "description": "Mantenimiento y limpieza programada para prevenir fallas",
  "type":"Service",
  "price": 8762
}


### Buscar todos los productos
GET http://localhost:5000/products
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDZhN2RlZGNhMjE2OGRhNTgwY2I3ZiIsImlhdCI6MTY5OTEzMjc3MCwiZXhwIjoxNjk5MTM5OTcwfQ.A0AROOfeAPE4z4efw_DwB3b08xFvpc17VFRQBtMop6c


### Buscar un producto por id
GET http://localhost:5000/products/65456306754f9595cbe63d6b


### Actualizar un cliente por id
PUT   http://localhost:5000/products/6545635b754f9595cbe63d6d
content-type: application/json

{
  "price": 10514
}


### Eliminar un producto por id
DELETE http://localhost:5000/clients/productId